<a href="https://colab.research.google.com/github/kingketan9/ApplicationsOfAI-Labs/blob/main/Ass4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Topic Modeling - Attempt 1 (All Text)

In [1]:
import pandas as pd 
import pickle

data = pd.read_pickle('dtm_stop.pkl')
data

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zee,zen,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,2,1,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,1,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [2]:
from gensim import matutils, models
import scipy.sparse

In [3]:
tdm = data.transpose()
tdm.head()

,ali,anthony,bill,bo,dave,hasan,jim,joe,john,louis,mike,ricky
aaaaah,0,0,1,0,0,0,0,0,0,0,0,0
aaaaahhhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaaauuugghhhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaaahhhhh,0,0,0,1,0,0,0,0,0,0,0,0
aaah,0,0,0,0,1,0,0,0,0,0,0,0

In [4]:
sparse_counts = scipy.sparse.csr_matrix(tdm)
corpus = matutils.Sparse2Corpus(sparse_counts)

In [5]:
cv = pickle.load(open("cv_stop.pkl", "rb"))
id2word = dict((v,k) for k, v in cv.vocabulary_.items())

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.18.2 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [6]:
lda = models.LdaModel(corpus = corpus, id2word = id2word, num_topics = 2, passes = 10)
lda.print_topics()

[(0,
  '0.007*"shit" + 0.007*"fucking" + 0.005*"going" + 0.005*"fuck" + 0.005*"want" + 0.005*"say" + 0.005*"hes" + 0.005*"didnt" + 0.005*"cause" + 0.005*"good"'),
 (1,
  '0.008*"fucking" + 0.006*"say" + 0.005*"fuck" + 0.005*"theyre" + 0.005*"little" + 0.004*"man" + 0.004*"theres" + 0.004*"hes" + 0.004*"going" + 0.004*"went"')]

In [7]:
lda = models.LdaModel(corpus = corpus, id2word = id2word, num_topics = 3, passes = 10)
lda.print_topics()

[(0,
  '0.006*"say" + 0.006*"day" + 0.005*"joke" + 0.005*"fucking" + 0.004*"little" + 0.004*"didnt" + 0.004*"went" + 0.004*"shit" + 0.004*"thing" + 0.004*"ive"'),
 (1,
  '0.008*"fucking" + 0.007*"shit" + 0.006*"going" + 0.006*"want" + 0.006*"fuck" + 0.005*"hes" + 0.005*"didnt" + 0.005*"good" + 0.005*"say" + 0.005*"thing"'),
 (2,
  '0.008*"fucking" + 0.007*"fuck" + 0.005*"theyre" + 0.005*"man" + 0.005*"little" + 0.005*"say" + 0.004*"shit" + 0.004*"real" + 0.004*"really" + 0.004*"way"')]

In [8]:
lda = models.LdaModel(corpus = corpus, id2word = id2word, num_topics = 4, passes = 10)
lda.print_topics()

[(0,
  '0.013*"fucking" + 0.008*"fuck" + 0.007*"shit" + 0.007*"theyre" + 0.006*"theres" + 0.006*"thing" + 0.006*"hes" + 0.006*"went" + 0.006*"say" + 0.006*"going"'),
 (1,
  '0.006*"want" + 0.006*"love" + 0.005*"shit" + 0.005*"dad" + 0.005*"fuck" + 0.005*"fucking" + 0.005*"good" + 0.005*"going" + 0.005*"man" + 0.005*"didnt"'),
 (2,
  '0.007*"shit" + 0.006*"ok" + 0.005*"lot" + 0.005*"wanna" + 0.005*"gotta" + 0.004*"husband" + 0.004*"cause" + 0.004*"day" + 0.004*"women" + 0.003*"pregnant"'),
 (3,
  '0.006*"say" + 0.006*"cause" + 0.005*"day" + 0.005*"really" + 0.005*"says" + 0.004*"didnt" + 0.004*"way" + 0.004*"mean" + 0.004*"goes" + 0.004*"good"')]

#Topic Modeling - Attempt 2 (Nouns Only)

In [9]:
from nltk import word_tokenize, pos_tag
import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

def nouns(text):
  '''Given a string of text, tokenize the text and pull out only the nouns'''
  is_noun = lambda pos: pos[:2] == 'NN'
  tokenized = word_tokenize(text)
  all_nouns = [word for (word,pos) in pos_tag(tokenized) if is_noun(pos)]
  return ' '.join(all_nouns)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.

In [10]:
data_clean = pd.read_pickle('data_clean.pkl')
data_clean

                                                transcript
ali      ladies and gentlemen please welcome to the sta...
anthony  thank you thank you thank you san francisco th...
bill      all right thank you thank you very much thank...
bo       bo what old macdonald had a farm e i e i o and...
dave     this is dave he tells dirty jokes for a living...
hasan      whats up davis whats up im home i had to bri...
jim         ladies and gentlemen please welcome to the ...
joe         ladies and gentlemen welcome joe rogan  wha...
john     all right petunia wish me luck out there you w...
louis    introfade the music out lets roll hold there l...
mike     wow hey thank you thanks thank you guys hey se...
ricky    hello hello how you doing great thank you wow ...

In [11]:
data_nouns = pd.DataFrame(data_clean.transcript.apply(nouns))
data_nouns

                                                transcript
ali      ladies gentlemen stage ali hi thank hello na s...
anthony  thank thank people i em i francisco city world...
bill     thank thank pleasure georgia area oasis i june...
bo       macdonald farm e i o farm pig e i i snort macd...
dave     jokes living stare work profound train thought...
hasan    whats davis whats home i netflix la york i son...
jim      ladies gentlemen stage mr jim jefferies thank ...
joe      ladies gentlemen joe fuck thanks phone fuckfac...
john     petunia thats hello hello chicago thank crowd ...
louis    music lets lights lights thank i i place place...
mike     wow hey thanks look insane years everyone i id...
ricky    hello thank fuck thank im gon youre weve money...

In [12]:
from sklearn.feature_extraction import text
from sklearn.feature_extraction.text import CountVectorizer

add_stop_words = ['like', 'im', 'know', 'just', 'dont', 'thats', 'right', 'people', 'youre', 'got', 'gonna', 'time', 'think', 'yeah', 'said']
stop_words = text.ENGLISH_STOP_WORDS.union(add_stop_words)

cvn = CountVectorizer(stop_words = stop_words)
data_cvn = cvn.fit_transform(data_nouns.transcript)
data_dtmn = pd.DataFrame(data_cvn.toarray(), columns = cvn.get_feature_names())
data_dtmn.index = data_nouns.index
data_dtmn

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abortion,abortions,abuse,...,yummy,ze,zealand,zee,zeppelin,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,2,0,0,...,0,0,10,0,0,0,0,0,0,0
bill,0,0,0,0,0,1,0,0,0,0,...,0,1,0,0,0,1,1,1,0,0
bo,1,1,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,0,0,0
ricky,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0

In [13]:
corpusn = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

id2wordn = dict((v,k) for k, v in cv.vocabulary_.items())

In [14]:
ldan = models.LdaModel(corpus = corpusn, id2word = id2wordn, num_topics = 2, passes = 10)
ldan.print_topics()

[(0,
  '0.007*"environmental" + 0.007*"chat" + 0.006*"champion" + 0.005*"michigan" + 0.005*"fastest" + 0.005*"doin" + 0.005*"opening" + 0.004*"noise" + 0.004*"fiveday" + 0.004*"ladies"'),
 (1,
  '0.009*"lamp" + 0.008*"michigan" + 0.008*"blam" + 0.008*"chat" + 0.008*"fiveday" + 0.007*"fastest" + 0.007*"dickinsons" + 0.007*"dana" + 0.007*"doin" + 0.006*"noise"')]

In [15]:
ldan = models.LdaModel(corpus = corpusn, id2word = id2wordn, num_topics = 3, passes = 10)
ldan.print_topics()

[(0,
  '0.007*"dicing" + 0.004*"chat" + 0.004*"defensive" + 0.003*"ammunition" + 0.003*"michigan" + 0.003*"ceramic" + 0.003*"disabilities" + 0.003*"offsides" + 0.003*"belief" + 0.003*"annoyed"'),
 (1,
  '0.006*"manny" + 0.006*"homebeachpubso" + 0.005*"aww" + 0.005*"noise" + 0.005*"blam" + 0.005*"intruder" + 0.004*"ex" + 0.004*"convinced" + 0.004*"dust" + 0.004*"gossip"'),
 (2,
  '0.010*"lamp" + 0.009*"michigan" + 0.009*"chat" + 0.009*"fastest" + 0.008*"fiveday" + 0.008*"doin" + 0.007*"dana" + 0.007*"noise" + 0.006*"field" + 0.006*"blam"')]

In [16]:
ldan = models.LdaModel(corpus = corpusn, id2word = id2wordn, num_topics = 4, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

#Topic Modeling - Attempt 3 (Nouns And Adjectives)

In [17]:
def nouns_adj(text):
  '''Given a string of text, tokenize the text and pull out the nouns and adjectives'''
  is_noun_adj = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ'
  tokenized = word_tokenize(text)
  nouns_adj = [word for (word,pos) in pos_tag(tokenized) if is_noun_adj(pos)]
  return ' '.join(nouns_adj)

In [18]:
data_nouns_adj = pd.DataFrame(data_clean.transcript.apply(nouns_adj))
data_nouns_adj

                                                transcript
ali      ladies gentlemen welcome stage ali wong hi wel...
anthony  thank san francisco thank good people surprise...
bill     right thank thank pleasure greater atlanta geo...
bo       old macdonald farm e i i o farm pig e i i snor...
dave     dirty jokes living stare most hard work profou...
hasan    whats davis whats im home i netflix special la...
jim      ladies gentlemen welcome stage mr jim jefferie...
joe      ladies gentlemen joe fuck san francisco thanks...
john     right petunia august thats good right hello he...
louis    music lets lights lights thank much i i i nice...
mike     wow hey thanks hey seattle nice look crazy ins...
ricky    hello great thank fuck thank lovely welcome im...

In [19]:
cvna = CountVectorizer(stop_words = stop_words, max_df = .8)
data_cvna = cvna.fit_transform(data_nouns_adj.transcript)
data_dtmna = pd.DataFrame(data_cvna.toarray(), columns = cvna.get_feature_names())
data_dtmna.index = data_nouns_adj.index
data_dtmna

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aah,abc,abcs,ability,abject,able,...,ze,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoo,éclair
ali,0,0,0,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,10,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,1,0,0
bo,0,1,1,1,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
dave,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,2,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,3,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,3,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,1,1,2,...,0,0,0,0,0,0,0,0,1,0

In [20]:
corpusna = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

id2wordna = dict((v,k) for k, v in cv.vocabulary_.items())

In [21]:
ldana = models.LdaModel(corpus = corpusna, id2word = id2wordna, num_topics = 2, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

In [22]:
ldana = models.LdaModel(corpus = corpusna, id2word = id2wordna, num_topics = 3, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

In [23]:
ldana = models.LdaModel(corpus = corpusna, id2word = id2wordna, num_topics = 4, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

#Identify Topics in Each Document

In [24]:
ldana = models.LdaModel(corpus = corpusna, id2word = id2wordna, num_topics = 4, passes = 80)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

In [25]:
corpus_transformed = ldana[corpusna]
list(zip([a for [(a,b)] in corpus_transformed], data_dtmna.index))

[(2, 'ali'),
 (0, 'anthony'),
 (3, 'bill'),
 (2, 'bo'),
 (2, 'dave'),
 (0, 'hasan'),
 (2, 'jim'),
 (0, 'joe'),
 (0, 'john'),
 (0, 'louis'),
 (1, 'mike'),
 (0, 'ricky')]

#Assignment

1. Try further modifying the parameters of the topic models above and see if you can get a better topics.

In [26]:
ldana = models.LdaModel(corpus = corpusna, id2word = id2wordna, num_topics = 5, passes = 100)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

2. Create a new topic model that includes terms from a different part of speech and see if u can get better topics

In [27]:
def nouns_adj_verb(text):
  '''Given a string of text, tokenize the text and pull out the nouns and adjectives'''
  is_noun_adj_verb = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ' or pos[:2] == 'VB'
  tokenized = word_tokenize(text)
  nouns_adj_verb = [word for (word,pos) in pos_tag(tokenized) if is_noun_adj_verb(pos)]
  return ' '.join(nouns_adj_verb)

In [28]:
data_nouns_adj_verb = pd.DataFrame(data_clean.transcript.apply(nouns_adj_verb))
data_nouns_adj_verb

                                                transcript
ali      ladies gentlemen please welcome stage ali wong...
anthony  thank thank thank san francisco thank good be ...
bill     right thank thank thank thank are whats going ...
bo       bo old macdonald had farm e i e i o farm had p...
dave     is dave tells dirty jokes living stare is most...
hasan    whats davis whats im home i had bring netflix ...
jim      ladies gentlemen please welcome stage mr jim j...
joe      ladies gentlemen welcome joe rogan fuck is goi...
john     right petunia wish die august thats good right...
louis    introfade music lets roll hold lights do light...
mike     wow hey thank thanks thank guys hey seattle ni...
ricky    hello hello doing great thank wow calm shut fu...

In [32]:
cvnav = CountVectorizer(stop_words = stop_words, max_df = .8)
data_cvnav = cvnav.fit_transform(data_nouns_adj_verb.transcript)
data_dtmnav = pd.DataFrame(data_cvnav.toarray(), columns = cvnav.get_feature_names())
data_dtmnav.index = data_nouns_adj_verb.index
data_dtmnav


# cvnav = CountVectorizer(stop_words = stop_words, max_df = .8)
# data_cvnav = cvnav.fit_transform(data_nouns_adj_verb.transcript)
# data_dtmnav = pd.DataFrame(data_cvnav.toarray(), columns = cvnav.get_feature_names())
# data_dtmnav.index = data_nouns_adj.index
# data_dtmnav

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaah,aaaaahhhhhhh,aaaaauuugghhhhhh,aaaahhhhh,aaah,aah,abc,abcs,ability,abject,...,zealand,zee,zeppelin,zero,zillion,zombie,zombies,zoning,zoo,éclair
ali,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,10,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,1,1,1,0,0
bo,0,1,1,1,0,0,0,0,1,0,...,0,0,0,1,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,3,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,1,0

In [33]:
corpusnav = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmn.transpose()))

id2wordnav = dict((v,k) for k, v in cv.vocabulary_.items())

In [34]:
ldanav = models.LdaModel(corpus = corpusnav, id2word = id2wordna, num_topics = 2, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

In [35]:
ldanav = models.LdaModel(corpus = corpusnav, id2word = id2wordnav, num_topics = 3, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

In [36]:
ldanav = models.LdaModel(corpus = corpusnav, id2word = id2wordnav, num_topics = 4, passes = 10)
ldan.print_topics()

[(0,
  '0.000*"michigan" + 0.000*"blam" + 0.000*"lamp" + 0.000*"chat" + 0.000*"field" + 0.000*"fiveday" + 0.000*"doin" + 0.000*"dickinsons" + 0.000*"mickey" + 0.000*"demons"'),
 (1,
  '0.013*"lamp" + 0.010*"fastest" + 0.010*"michigan" + 0.009*"doin" + 0.008*"demons" + 0.007*"blam" + 0.007*"dickinsons" + 0.007*"chat" + 0.007*"collectively" + 0.007*"field"'),
 (2,
  '0.011*"chat" + 0.010*"michigan" + 0.007*"environmental" + 0.006*"blam" + 0.006*"mickey" + 0.006*"noise" + 0.005*"doin" + 0.005*"fiveday" + 0.005*"dust" + 0.005*"offsides"'),
 (3,
  '0.009*"fiveday" + 0.009*"lamp" + 0.008*"dana" + 0.008*"champion" + 0.007*"noise" + 0.007*"fastest" + 0.006*"driving" + 0.006*"ladies" + 0.006*"doin" + 0.006*"gambit"')]

3. Do the same thing with 2-gram  model

In [42]:
def nouns_adj_verb(text):
    '''Given a string of text, tokenize the text and pull out the nouns and adjectives'''
    is_noun_adj_verb = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ' or pos[:2] == 'VB'
    tokenized = word_tokenize(text)
    nouns_adj_verb = [word for (word,pos) in pos_tag(tokenized) if is_noun_adj_verb(pos)]
    return ' '.join(nouns_adj_verb)

In [43]:
data_nouns_adj_verb = pd.DataFrame(data_clean.transcript.apply(nouns_adj_verb))
data_nouns_adj_verb

                                                transcript
ali      ladies gentlemen please welcome stage ali wong...
anthony  thank thank thank san francisco thank good be ...
bill     right thank thank thank thank are whats going ...
bo       bo old macdonald had farm e i e i o farm had p...
dave     is dave tells dirty jokes living stare is most...
hasan    whats davis whats im home i had bring netflix ...
jim      ladies gentlemen please welcome stage mr jim j...
joe      ladies gentlemen welcome joe rogan fuck is goi...
john     right petunia wish die august thats good right...
louis    introfade music lets roll hold lights do light...
mike     wow hey thank thanks thank guys hey seattle ni...
ricky    hello hello doing great thank wow calm shut fu...

In [44]:
cvnav = CountVectorizer(stop_words=stop_words, max_df=0.8, ngram_range=(2,2))  
data_cvnav = cvnav.fit_transform(data_nouns_adj_verb.transcript) 
data_dtmnav = pd.DataFrame(data_cvnav.toarray(), columns=cvnav.get_feature_names())
data_dtmnav.index = data_nouns_adj_verb.index
data_dtmnav

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaah anybody,aaaaahhhhhhh god,aaaaauuugghhhhhh hard,aaaahhhhh aaaaahhhhhhh,aaah shit,aah aah,aah ones,abc great,abcs hey,ability speak,...,zeppelin minutes,zero isolation,zero value,zillion bucks,zombie coming,zombie hippies,zombies backup,zoning laws,zoo looking,éclair talk
ali,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,0,1,0,...,0,0,0,1,1,0,1,1,0,0
bo,0,1,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,2,1,0,0,0,...,0,0,1,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0

In [45]:
corpusnav = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmnav.transpose())) 

id2wordnav = dict((v,k) for k, v in cvnav.vocabulary_.items())

In [46]:
ldanav = models.LdaModel(corpus=corpusnav, id2word=id2wordnav, num_topics=2, passes=10)
ldanav.print_topics()

[(0,
  '0.001*"new york" + 0.000*"wan na" + 0.000*"oh god" + 0.000*"ha ha" + 0.000*"bruce jenner" + 0.000*"thank thank" + 0.000*"gon happen" + 0.000*"san francisco" + 0.000*"gon na" + 0.000*"new zealand"'),
 (1,
  '0.001*"repeat stuff" + 0.001*"ahah ahah" + 0.001*"eye contact" + 0.001*"stuff repeat" + 0.001*"prolonged eye" + 0.001*"white house" + 0.001*"contact prolonged" + 0.000*"fuck fuck" + 0.000*"business class" + 0.000*"bo bo"')]

In [47]:
ldanav = models.LdaModel(corpus=corpusnav, id2word=id2wordnav, num_topics=3, passes=10)
ldanav.print_topics()

[(0,
  '0.001*"new york" + 0.001*"wan na" + 0.001*"oh god" + 0.000*"san francisco" + 0.000*"new zealand" + 0.000*"mom dad" + 0.000*"hasan bhai" + 0.000*"thank thank" + 0.000*"jesus christ" + 0.000*"buy cow"'),
 (1,
  '0.001*"repeat stuff" + 0.001*"stuff repeat" + 0.001*"prolonged eye" + 0.001*"eye contact" + 0.001*"contact prolonged" + 0.000*"bo bo" + 0.000*"bruce jenner" + 0.000*"ha ha" + 0.000*"business class" + 0.000*"wan na"'),
 (2,
  '0.001*"ahah ahah" + 0.001*"white house" + 0.001*"ahah ghetto" + 0.001*"fuck fuck" + 0.000*"ghetto ahah" + 0.000*"united states" + 0.000*"dave chappelle" + 0.000*"jenny says" + 0.000*"whats going" + 0.000*"theyre gon"')]

In [48]:
ldanav = models.LdaModel(corpus=corpusnav, id2word=id2wordnav, num_topics=4, passes=10)
ldanav.print_topics()

[(0,
  '0.001*"ahah ahah" + 0.001*"wan na" + 0.001*"oh god" + 0.001*"business class" + 0.001*"ahah ghetto" + 0.000*"ghetto ahah" + 0.000*"ha ha" + 0.000*"dave chappelle" + 0.000*"good night" + 0.000*"south africa"'),
 (1,
  '0.002*"repeat stuff" + 0.002*"stuff repeat" + 0.001*"prolonged eye" + 0.001*"eye contact" + 0.001*"contact prolonged" + 0.001*"bo bo" + 0.001*"left brain" + 0.001*"mr finch" + 0.001*"buy cow" + 0.000*"new york"'),
 (2,
  '0.001*"white house" + 0.001*"jenny says" + 0.001*"fuck fuck" + 0.000*"santa claus" + 0.000*"stop ride" + 0.000*"theyre gon" + 0.000*"new york" + 0.000*"wan na" + 0.000*"whats going" + 0.000*"nonmakeout club"'),
 (3,
  '0.001*"new york" + 0.001*"bruce jenner" + 0.000*"new zealand" + 0.000*"thank thank" + 0.000*"hasan bhai" + 0.000*"mom dad" + 0.000*"pizza hut" + 0.000*"san francisco" + 0.000*"jesus christ" + 0.000*"shark party"')]

4. Do the same thing with 3-gram  model

In [49]:
def nouns_adj_verb(text):
    '''Given a string of text, tokenize the text and pull out the nouns and adjectives'''
    is_noun_adj_verb = lambda pos: pos[:2] == 'NN' or pos[:2] == 'JJ' or pos[:2] == 'VB'
    tokenized = word_tokenize(text)
    nouns_adj_verb = [word for (word,pos) in pos_tag(tokenized) if is_noun_adj_verb(pos)]
    return ' '.join(nouns_adj_verb)

In [50]:
data_nouns_adj_verb = pd.DataFrame(data_clean.transcript.apply(nouns_adj_verb))
data_nouns_adj_verb

                                                transcript
ali      ladies gentlemen please welcome stage ali wong...
anthony  thank thank thank san francisco thank good be ...
bill     right thank thank thank thank are whats going ...
bo       bo old macdonald had farm e i e i o farm had p...
dave     is dave tells dirty jokes living stare is most...
hasan    whats davis whats im home i had bring netflix ...
jim      ladies gentlemen please welcome stage mr jim j...
joe      ladies gentlemen welcome joe rogan fuck is goi...
john     right petunia wish die august thats good right...
louis    introfade music lets roll hold lights do light...
mike     wow hey thank thanks thank guys hey seattle ni...
ricky    hello hello doing great thank wow calm shut fu...

In [51]:
cvnav = CountVectorizer(stop_words=stop_words, max_df=0.8, ngram_range=(3,3))  
data_cvnav = cvnav.fit_transform(data_nouns_adj_verb.transcript) 
data_dtmnav = pd.DataFrame(data_cvnav.toarray(), columns=cvnav.get_feature_names())
data_dtmnav.index = data_nouns_adj_verb.index
data_dtmnav

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,aaaaah anybody shout,aaaaahhhhhhh god ahhhhh,aaaaauuugghhhhhh hard lizard,aaaahhhhh aaaaahhhhhhh god,aaah shit scary,aah aah aah,aah aah ones,aah ones die,abc great love,abcs hey savage,...,zeppelin minutes great,zero isolation complete,zero value sexual,zillion bucks gets,zombie coming street,zombie hippies hey,zombies backup everybody,zoning laws theyll,zoo looking started,éclair talk child
ali,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
anthony,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
bill,1,0,0,0,0,0,0,0,0,1,...,0,0,0,1,1,0,1,1,0,0
bo,0,1,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
dave,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hasan,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
jim,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
joe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
john,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
louis,0,0,0,0,0,1,1,1,0,0,...,0,0,1,0,0,0,0,0,0,0
mike,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
ricky,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [52]:
corpusnav = matutils.Sparse2Corpus(scipy.sparse.csr_matrix(data_dtmnav.transpose())) 

id2wordnav = dict((v,k) for k, v in cvnav.vocabulary_.items())

In [53]:
ldanav = models.LdaModel(corpus=corpusnav, id2word=id2wordnav, num_topics=2, passes=10)
ldanav.print_topics()

[(0,
  '0.001*"stuff repeat stuff" + 0.001*"repeat stuff repeat" + 0.001*"prolonged eye contact" + 0.001*"eye contact prolonged" + 0.001*"contact prolonged eye" + 0.000*"fuck fuck fuck" + 0.000*"bo bo bo" + 0.000*"log kya kahenge" + 0.000*"hey walk home" + 0.000*"broke white house"'),
 (1,
  '0.000*"ahah ahah ghetto" + 0.000*"ahah ahah ahah" + 0.000*"ahah ghetto ahah" + 0.000*"ghetto ahah ahah" + 0.000*"ha ha ha" + 0.000*"wan na work" + 0.000*"business class ticket" + 0.000*"met oj simpson" + 0.000*"thank thank thank" + 0.000*"whats gon happen"')]

In [54]:
ldanav = models.LdaModel(corpus=corpusnav, id2word=id2wordnav, num_topics=3, passes=10)
ldanav.print_topics()

[(0,
  '0.001*"stuff repeat stuff" + 0.001*"repeat stuff repeat" + 0.001*"prolonged eye contact" + 0.001*"contact prolonged eye" + 0.001*"eye contact prolonged" + 0.000*"fuck fuck fuck" + 0.000*"bo bo bo" + 0.000*"ha ha ha" + 0.000*"broke white house" + 0.000*"magic isnt real"'),
 (1,
  '0.000*"ahah ahah ghetto" + 0.000*"ahah ahah ahah" + 0.000*"ahah ghetto ahah" + 0.000*"ghetto ahah ahah" + 0.000*"log kya kahenge" + 0.000*"met oj simpson" + 0.000*"tools clear history" + 0.000*"hey walk home" + 0.000*"real estate agent" + 0.000*"theres lot men"'),
 (2,
  '0.000*"wan na work" + 0.000*"business class ticket" + 0.000*"dead baby jokes" + 0.000*"thank thank thank" + 0.000*"half months pregnant" + 0.000*"harvard business school" + 0.000*"fuck fuck fuck" + 0.000*"bad report card" + 0.000*"sit sit sit" + 0.000*"live los angeles"')]

In [55]:
ldanav = models.LdaModel(corpus=corpusnav, id2word=id2wordnav, num_topics=4, passes=10)
ldanav.print_topics()

[(0,
  '0.000*"stuff repeat stuff" + 0.000*"repeat stuff repeat" + 0.000*"contact prolonged eye" + 0.000*"eye contact prolonged" + 0.000*"ahah ahah ahah" + 0.000*"ahah ahah ghetto" + 0.000*"prolonged eye contact" + 0.000*"fuck fuck fuck" + 0.000*"ahah ghetto ahah" + 0.000*"thank thank thank"'),
 (1,
  '0.001*"repeat stuff repeat" + 0.001*"stuff repeat stuff" + 0.001*"prolonged eye contact" + 0.001*"eye contact prolonged" + 0.001*"contact prolonged eye" + 0.001*"ahah ahah ghetto" + 0.000*"ahah ahah ahah" + 0.000*"ahah ghetto ahah" + 0.000*"ghetto ahah ahah" + 0.000*"bo bo bo"'),
 (2,
  '0.000*"fuck fuck fuck" + 0.000*"log kya kahenge" + 0.000*"wan na work" + 0.000*"broke white house" + 0.000*"tools clear history" + 0.000*"half months pregnant" + 0.000*"harvard business school" + 0.000*"doesnt make sense" + 0.000*"earth years old" + 0.000*"want change life"'),
 (3,
  '0.000*"business class ticket" + 0.000*"hey walk home" + 0.000*"scients wont help" + 0.000*"bruce jenner went" + 0.000*"real estate agent" + 0.000*"ha ha ha" + 0.000*"disgraced nuclear physicist" + 0.000*"fucker doing boy" + 0.000*"real estate agents" + 0.000*"wan na say"')]